### ISSUE TITLE
Duplicate symbols for architecture x86_64 - MacOS 10.12.4

### ISSUE THREAD

**Issue by Thireus** [opcm/pcm#28] opened 2017-04-06 08:38 UTC
Duplicate symbol errors occur when the pcm utilities from the root directory are compiled:

```
make
c++ -Wall -g -O3 -Wno-unknown-pragmas -I/usr/include -IMacMSRDriver -std=c++0x -c pcm-numa.cpp -o pcm-numa.o
c++ -MM -Wall -g -O3 -Wno-unknown-pragmas -I/usr/include -IMacMSRDriver -std=c++0x pcm-numa.cpp > pcm-numa.d
c++ -Wall -g -O3 -Wno-unknown-pragmas -I/usr/include -IMacMSRDriver -std=c++0x -c msr.cpp -o msr.o

[...]

duplicate symbol std::vector<TopologyEntry, std::allocator<TopologyEntry> >::operator=(std::initializer_list<TopologyEntry>) in:
    pcm-numa.o
    utils.o
duplicate symbol std::vector<TopologyEntry, std::allocator<TopologyEntry> >::assign(std::initializer_list<TopologyEntry>) in:
    pcm-numa.o
    utils.o
duplicate symbol std::vector<TopologyEntry, std::allocator<TopologyEntry> >::insert(__gnu_cxx::__normal_iterator<TopologyEntry const*, std::vector<TopologyEntry, std::allocator<TopologyEntry> > >, std::initializer_list<TopologyEntry>) in:
    pcm-numa.o
    utils.o
ld: 522 duplicate symbols for architecture x86_64
collect2: error: ld returned 1 exit status
make: *** [pcm-numa.x] Error 1
```

For some reason the following lines are defined in cpucounters.h and must be removed in order to compile the utilities without duplicate symbol errors:

```
#ifndef HACK_TO_REMOVE_DUPLICATE_ERROR
template class PCM_API std::allocator<TopologyEntry>;
template class PCM_API std::vector<TopologyEntry>;
template class PCM_API std::allocator<CounterWidthExtender *>;
template class PCM_API std::vector<CounterWidthExtender *>;
template class PCM_API std::allocator<uint32>;
template class PCM_API std::vector<uint32>;
template class PCM_API std::allocator<char>;
#endif
```

Alternatively HACK_TO_REMOVE_DUPLICATE_ERROR must be defined somewhere for these lines to be silent during compilation (which is actually something already in place when compiling MacMSRDriver lib and driver).

When the above lines are removed (AFTER compiling the libPcmMsr.dylib from the MacMSRDriver directory) the utilities are compiled successfully.

**Comment by opcm** [comment] 2017-04-06 10:21
I am not sure why we don't have this issue on Travis CI OS X build: https://travis-ci.org/opcm/pcm/jobs/217597469

...

**Comment by opcm** [comment] 2017-04-07 08:58
HACK_TO_REMOVE_DUPLICATE_ERROR is already defined that should silence the lines:
https://github.com/opcm/pcm/search?utf8=%E2%9C%93&q=HACK_TO_REMOVE_DUPLICATE_ERROR&type=

I can not reproduce it neither with clang nor g++: https://travis-ci.org/opcm/pcm

It seems to be a compiler bug for me. Could you try a different compiler?

**Comment by opcm** [comment] 2017-04-19 12:50
closing now (seem to be not reproducible)

**Closed by opcm** 2017-04-19 12:50 UTC
Labels: invalid
