### ISSUE TITLE
Support Intel latest Xeon SP Sapphire Rapids CPU of the eagle stream platform

### ISSUE THREAD

**Issue by hualong1009** [opcm/pcm#397] opened 2022-04-08 10:17 UTC
> Processor Counter Monitor  (2022-01-10 12:00:20 +0100 ID=799a3f6)
>
>
>Linux arch_perfmon flag  : yes
Hybrid processor         : no
IBRS and IBPB supported  : yes
STIBP supported          : yes
Spec arch caps supported : yes
Error: unsupported processor. Only Intel(R) processors are supported (Atom(R) and microarchitecture codename Nehalem/Nehalem-EP, Atom(tm), Westmere/Clarkdale, Sandy Bridge, Westmere-EP, Sandy Bridge-EP/Jaketown, Nehalem-EX, Westmere-EX, unknown, Centerton, Baytrail, Ivy Bridge, Haswell, Broadwell, Ivy Bridge-EP/EN/EX/Ivytown, Haswell-EP/EN/EX, Cherrytrail, Avoton, Skylake U/Y, Broadwell-EP/EX, Skylake-SP, Cascade Lake-SP, Broadwell-DE, Knights Landing, Apollo Lake, Skylake, Denverton, Icelake-SP, Icelake, Snowridge, Tiger Lake, Kabylake/Whiskey Lake, Alder Lake, Kabylake, Comet Lake, Rocket Lake). CPU model number: 143 Brand: "Genuine Intel(R) CPU 0000%@"
Disabling NMI watchdog since it consumes one hw-PMU counter.
Access to Processor Counter Monitor has denied (no MSR or PCI CFG space access).
#

These cpus are samples of the ES2 phase, so show 'CPU model number: 143 Brand: "Genuine Intel(R) CPU 0000%@"'

**Comment by opcm** [comment] 2022-04-08 11:11
duplicate of https://github.com/opcm/pcm/issues/396

**Closed by opcm** 2022-04-08 11:11 UTC
